seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444
  environment:
    - GRID_TIMEOUT=45
    - GRID_BROWSER_TIMEOUT=90



chromenode:
  image: selenium/node-chrome
  ports:
    - 5900
  links:
    - seleniumhub:hub
  volumes:
    - /dev/shm:/dev/shm

